/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AliceHoldemPoker;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Engine classUnderTest = new Engine();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
